#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(LALT(KC_P), LALT(KC_W), KC_NO, LALT(KC_C), LALT(KC_V), RALT(KC_R), MO(1), KC_F10, KC_F12, KC_MUTE, KC_VOLD, KC_VOLU),
	[1] = LAYOUT(LALT(KC_1), LALT(KC_2), LALT(KC_3), LALT(KC_4), LALT(KC_5), LALT(KC_6), KC_TRNS, LALT(KC_7), LALT(KC_8), LALT(KC_9), LALT(KC_0), KC_TRNS)
};

